export const GET_CITIES_FROM_API = 'GET_CITIES_FROM_API';
export const GET_CITY_ERROR = 'GET_CITIES_ERROR';
export const SELECT_CITY = 'SELECT_CITY';


export const SELECT_CURRENCY = 'SELECT_CURRENCY';
export const GET_EXCHANGE_CURRENCY_SUCCESS = 'GET_EXCHANGE_CURRENCY_SUCCESS';
export const GET_EXCHANGE_CURRENCY_ERROR = 'GET_EXCHANGE_CURRENCY_ERROR';


export const GET_ALL_CRYPTOCURRENCIES = 'GET_ALL_CRYPTOCURRENCIES';
export const GET_ALL_CRYPTOCURRENCIES_SUCCESS = 'GET_ALL_CRYPTOCURRENCIES_SUCCESS';
export const GET_ALL_CRYPTOCURRENCIES_ERROR = 'GET_ALL_CRYPTOCURRENCIES_ERROR';

export const SORT_HIGHEST = 'SORT_HIGHEST';
export const SORT_LOWEST = 'SORT_LOWEST';

export const SELECT_DATA_CHART = 'SELECT_DATA_CHART';
export const GET_DATA_CHART_SUCCESS_NOW = 'GET_DATA_CHART_SUCCESS_NOW';
export const GET_DATA_CHART_ERROR_NOW = 'GET_DATA_CHART_ERROR_NOW';

export const GET_DATA_CHART_SUCCESS_YESTERDAY = 'GET_DATA_CHART_SUCCESS_YESTERDAY';
export const GET_DATA_CHART_ERROR_YESTERDAY = 'GET_DATA_CHART_ERROR_YESTERDAY';
export const CONSOLIDATE_DATA = 'CONSOLIDATE_DATA';
